MYSQL_USERNAME = "root"
MYSQL_PASSWORD = "123"
MYSQL_HOST = "mysqldb"
MYSQL_PORT = "3306"
MYSQL_DATABASE = "database"


POSTGRES_USERNAME = "root"
POSTGRES_PASSWORD = "123"
POSTGRES_HOST = "postgresdb"
POSTGRES_PORT = "5432"
POSTGRES_DATABASE = "postgres"
